/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";
import * as THREE from "three";
import { useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Laptop(props) {
  const { nodes, materials } = useGLTF("models/Laptop.glb");
  const { angle } = useControls({
    angle: {
      min: 0,
      step: 1,
      value: 105,
    },
  });
  const scroll = useScroll();
  const screenRef = useRef();
  const start = 0.75;
  const end = 1;

  useFrame(() => {
    const totalPages = scroll.pages;
    const offset = scroll.offset;

    // Rotation values
    const CLOSED = THREE.MathUtils.degToRad(105);
    const OPEN = 0;

    // -----------------------------
    // 1️⃣ OPENING (page 0 → page 1)
    // -----------------------------
    const openStart = 0;
    const openEnd = 1 / totalPages;

    const openT = THREE.MathUtils.clamp(
      (offset - openStart) / (openEnd - openStart),
      0,
      1
    );

    // -----------------------------
    // 2️⃣ CLOSING (last page)
    // -----------------------------
    const closeStart = (totalPages - 1) / totalPages;
    const closeEnd = 1;

    const closeT = THREE.MathUtils.clamp(
      (offset - closeStart) / (closeEnd - closeStart),
      0,
      1
    );

    // -----------------------------
    // 3️⃣ DECIDE WHICH STATE WINS
    // -----------------------------
    let rotationX = OPEN;

    // Before fully opened → opening animation
    if (offset < openEnd) {
      rotationX = THREE.MathUtils.lerp(CLOSED, OPEN, openT);
    }
    // During last page → closing animation
    else if (offset > closeStart) {
      rotationX = THREE.MathUtils.lerp(OPEN, CLOSED, closeT);
    }
    // Otherwise → stay open
    else {
      rotationX = OPEN;
    }

    screenRef.current.rotation.x = rotationX;
  });

  return (
    <group {...props} dispose={null} receiveShadow castShadow>
      <group
        ref={screenRef}
        position={[-0.452, 4.947, -27.062]}
        rotation={[THREE.MathUtils.degToRad(angle), 0, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ChamferBox017_1005.geometry}
          material={materials["05___Default.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ChamferBox017_1005_1.geometry}
          material={materials["04___Default.002"]}
        >
          {/* <meshBasicMaterial color={"red"} /> */}
        </mesh>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferBox017_1004.geometry}
        material={materials["03___Default.002"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferBox017_1004_1.geometry}
        material={materials["05___Default.002"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ChamferBox017_1004_2.geometry}
        material={materials["01___Default.002"]}
      />
    </group>
  );
}

useGLTF.preload("models/Laptop.glb");
