/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";
import { useFrame } from "@react-three/fiber";
import { useControls } from "leva";
export function Mug(props) {
  const { nodes, materials } = useGLTF("models/mug.glb");

  const steamRef = useRef();

  const texture = useTexture("textures/steam.jpg");
  texture.repeat.set(1, 1);
  texture.wrapS = texture.wrapT = THREE.RepeatWrapping;

  useFrame((_, delta) => {
    texture.offset.y += delta * 0.15;

    // Optional: slowly rotate the steam for organic look
    if (steamRef.current) {
      steamRef.current.rotation.y += delta * 0.1;
    }
  });

  const { smoke_position, smoke_scale, smoke_opacity } = useControls({
    smoke_position: {
      x: 3.1,
      y: 5.7,
      z: 0.6,
    },
    smoke_scale: {
      x: 0.3,
      y: 1,
      z: 0.3,
    },
    smoke_opacity: {
      value: 0.3,
      min: 0,
      max: 1,
      step: 0.05,
    },
  });

  // Create multiple smoke planes at different angles for volumetric effect
  const smokePlanes = [0, 45, 90, 135].map((angle) => (
    <mesh key={angle} rotation={[0, (angle * Math.PI) / 180, 0]}>
      <planeGeometry args={[1, 1]} />
      <meshBasicMaterial
        map={texture}
        side={THREE.DoubleSide}
        opacity={smoke_opacity}
        depthWrite={false}
        blending={THREE.AdditiveBlending}
        transparent
      />
    </mesh>
  ));
  return (
    <>
      {/* Steam effect group */}
      {/* <group
        ref={steamRef}
        position={[smoke_position.x, smoke_position.y, smoke_position.z]}
        scale={[smoke_scale.x, smoke_scale.y, smoke_scale.z]}
      >
        {smokePlanes}
      </group> */}
      <group {...props} dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004.geometry}
          material={materials["07___Default"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_1.geometry}
          material={materials["02___Default"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_1_1.geometry}
          material={materials["08___Default"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Arc002_1.geometry}
          material={materials["08___Default-2"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Arc002_1_1.geometry}
          material={materials["02___Default-2"]}
        />
      </group>
    </>
  );
}

useGLTF.preload("models/mug.glb");
